### ISSUE TITLE
载入plugin失败报错 java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by Zhaokugua** [liujiaqi7998/GrasscuttersWebDashboard#2]
22:57:45 <INFO:DropManager> Drop data successfully loaded.
22:57:45 <INFO:ExpeditionManager> Expedition reward successfully loaded.
22:57:45 <INFO:PluginManager> Loading plugin: GrasscuttersWebDashboard
22:57:45 <INFO:GrasscuttersWebDashboard> [WEB控制台] 已保存默认配置文件
Exception in thread "main" java.lang.NoSuchMethodError: 'emu.grasscutter.Config emu.grasscutter.Grasscutter.getConfig()'
        at top.cyqi.GrasscuttersWebDashboard.onLoad(GrasscuttersWebDashboard.java:82)
        at emu.grasscutter.plugin.PluginManager.loadPlugin(PluginManager.java:119)
        at emu.grasscutter.plugin.PluginManager.lambda$loadPlugins$2(PluginManager.java:88)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.grasscutter.plugin.PluginManager.loadPlugins(PluginManager.java:63)
        at emu.grasscutter.plugin.PluginManager.<init>(PluginManager.java:29)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:109)
^CException in thread "Thread-1" java.lang.NullPointerException: Cannot invoke "emu.grasscutter.plugin.PluginManager.invokeEvent(emu.grasscutter.server.event.Event)" because the return value of "emu.grasscutter.Grasscutter.getPluginManager()" is null
        at emu.grasscutter.server.event.Event.call(Event.java:30)
        at emu.grasscutter.server.game.GameServer.onServerShutdown(GameServer.java:252)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by liujiaqi7998** [comment]
更新一下Grasscutters版本试试，这个插件是针对DEV版本开发的
我运行的版本是：grasscutter-220510-dev+bf3d6b3c.jar

**Comment by Zhaokugua** [comment]
https://t.me/GrasscutterArchives/264
用的是这个tg频道自动构建的dev版本，今晚22:30刚构建的，按道理讲应该没问题鸭qwq
我去试试你的版本

**Comment by liujiaqi7998** [comment]
好像版本存在差异
试试这里的版本：
https://juga-my.sharepoint.com/personal/wansn_juga_onmicrosoft_com/_layouts/15/onedrive.aspx?ga=1&isAscending=false&id=%2Fpersonal%2Fwansn%5Fjuga%5Fonmicrosoft%5Fcom%2FDocuments%2Fshare%2FGrasscutter%2FCore&sortField=Modified

**Comment by Zhaokugua** [comment]
确实是版本问题，换回去版本就能用啦~
希望能尽快跟进新版w
